# Generated by Django 6.0 on 2026-02-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_alter_comments_post_alter_comments_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
